### PR TITLE
fix: translate remained code comments to Chinese

### PR DESCRIPTION
**Pull request by aaaaaaMao**

### CODE REVIEW

**Comment by aaaaaaMao** [comment]
Sir, I can't translate comment "// Simple polify" exactly. Can you please give me some hints?

**Comment by gibbok** [comment]
Hi sure, here a definition
https://developer.mozilla.org/en-US/docs/Glossary/Polyfill

using a translator I receive this:

`JavaScript 兼容性填充` could it make sense?

Thanks for your help on this!

**Comment by aaaaaaMao** [comment]
OK，thank you, Sir. I couldn't find the word 'polify' in the dictionary, so I am asking you here about its meaning. I have guessed it to be the word 'polifill'. I will complete it.

**Review by gibbok — APPROVED** [review]
Many thanks!

**Pull request merged**
